//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIPCream.Presentation.WUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDiscipline
    {
        public int UserDisciplineId { get; set; }
        public int UsereId { get; set; }
        public int DisciplineId { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Users Users { get; set; }
    }
}
